### ISSUE TITLE
Unable to have any .json files in test-environment folder

### ISSUE THREAD

**Issue by davidshrive** [datasift/storyplayer#183]
Hey Stuart, 

Here at Datasift we recently experimented with the newer test-environment method of having a unique dsbuild/vagrant/config etc within each test environment folder and came across this blocking issue.

If you have any .json files within a test-environment folder storyplayer they are incorrectly assumed to be storyplayer config files and cause storyplayer to fail because they aren't valid. This is the error that is thrown...

```
*** error: environment has no 'groups' array

This was caused by an unexpected exception DataSift\Storyplayer\TestEnvironmentsLib\E4xx_TestEnvironmentNeedsGroups

#0 /Users/davidshrive/storyplayer/src/php/DataSift/Storyplayer/ConfigLib/ConfigList.php(195): DataSift\Storyplayer\TestEnvironmentsLib\TestEnvironmentConfig->validateConfig()
#1 /Users/davidshrive/storyplayer/src/php/DataSift/Storyplayer/ConfigLib/ConfigList.php(165): DataSift\Storyplayer\ConfigLib\ConfigList->loadJsonConfig('storyplayer/tes...')
#2 /Users/davidshrive/storyplayer/src/bin/storyplayer(255): DataSift\Storyplayer\ConfigLib\ConfigList->findConfigs()
#3 /Users/davidshrive/storyplayer/src/bin/storyplayer(361): main(Array)
#4 {main}
```

Here is a link to the file with the issue -> [Link](https://github.com/datasift/storyplayer/blob/develop/src/php/DataSift/Storyplayer/ConfigLib/ConfigList.php#L195)

and I've created a branch to demo the issue, just try and run the storyplayer test suite on the following branch...

https://github.com/datasift/storyplayer/tree/bug/unable-to-have-json-in-test-environment

Thanks

**Comment by stuartherbert** [comment]
Hi David,

I’ll take a look at it this evening for you.

Best regards,
Stu
--

**Comment by davidshrive** [comment]
Did you get chance to look into this @stuartherbert ?
